# -*- coding: utf-8 -*-
"""Number Guesser Game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wfQH0afpAl4wt0sM4ZocjmZe6uWpdbWR
"""

# Import required libraries for the gaming purposes.
import random
import time

# Few exciting commands to feel like a real game.
print('Hi, I am Nick, your AI assistant to this number guessing game. I am going to pick a number between 1 and 100.')
# Sleep function is used to show that your AI assistant is thinking in a like a real game.
time.sleep(3) 
print('Picking a number...')
time.sleep(2)
print('Ok, I am ready now. Your time begins now. You will be monitored while the game proceeds.')
time.sleep(2)

# Declaration of important variables used in the program.
correct_number = random.randint(1,100)
guess_count = 1

start_time = time.time()
guess = int(input('What is your guess?: '))
while (guess != correct_number):
  time.sleep(1)
  guess_count += 1
  if guess< correct_number:
    guess = int(input('Wrong. You need to guess higher. What is your guess?: '))
  else:
    guess = int(input('Wrong. You need to guess lower. What is your guess?: '))
end_time = time.time()

time_taken = end_time - start_time

print(f'Congrats. You got the right answer! {correct_number} is the right answer. It took you {guess_count} guesses. Further, you took {time_taken} seconds to guess the right answer.')